language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"

env:
  - DJANGO_VERSION=2.0.0
  - DJANGO_VERSION=1.11.0
  - DJANGO_VERSION=1.10.0

install:
  - pip install Django==$DJANGO_VERSION --quiet
  - pip install -r test-requirements.txt

before_script:
  - flake8  --ignore=E501

script:
  - coverage run runtests.py
  - python setup.py build

after_success:
  - coveralls
